import React, {Component} from 'react';

import Navigation from '../navigation';
import Footer from '../footer';

export default class Aviso extends Component {
    render(){
        return(
            <section className="Aviso">
                <Navigation />
                <div className="Aviso-text">
                    <h2 className="Aviso-title">AVISO DE PRIVACIDAD</h2>
                    <p className="Aviso-paragraph">En cumplimiento a lo establecido por la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (en lo sucesivo la “Ley”), el Reglamento de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares (en lo sucesivo el “Reglamento”), así como de los Lineamientos del Aviso de Privacidad (en lo sucesivo los “Lineamientos”), se hace de su conocimiento que <span>GRUPO INMOBILIARIO AFERBA, S.A.P.I. DE C.V.</span> (en lo sucesivo “La Empresa”) respeta el derecho a la privacidad y protección de datos personales, por lo que pone a su disposición el presente Aviso de Privacidad, a fin de que tenga pleno conocimiento sobre el tratamiento que se le dará a sus datos personales, así como facilitarle el ejercicio de los derechos que la Ley, el Reglamento y los Lineamientos le otorgan.</p>
                    <h3 className="Aviso-title Aviso-title--left">IDENTIDAD Y DOMICILIO DEL RESPONSABLE:</h3>
                    <p className="Aviso-paragraph">La Empresa es la responsable del uso, tratamiento y protección de sus datos personales, con domicilio en Periférico Sur número 4225, Oficina 203, Col. Jardines en la Montaña, Delegación Tlalpan, C.P. 14210, en la Ciudad de México.</p>
                    <h3 className="Aviso-title Aviso-title--left">DATOS PERSONALES TRATADOS POR LA EMPRESA:</h3>
                    <p className="Aviso-paragraph">Los datos personales que La Empresa recaba y trata incluyen nombres, apellidos, fecha de nacimiento, estado civil, domicilios, teléfonos de casa y/u oficina, celular, correos electrónicos, claves del registro federal de contribuyentes, información de formas de pago; toda aquella información que el titular le ha proporcionado y/o le proporcione a lo largo de la relación contractual o comercial que establezcan; aquellos datos propios y relacionados con los bienes que La Empresa comercializa.</p>
                    <p className="Aviso-paragraph">Al proporcionarnos sus datos personales por nuestra página web www.wiseliving.com.mx manifiesta que ha leído, entendido y está de acuerdo con nuestro Aviso de Privacidad y por consiguiente otorga su consentimiento para el tratamiento de sus datos personales conforme a los términos del mismo.</p>
                    <h3 className="Aviso-title Aviso-title--left">FINALIDADES DEL TRATAMIENTO DE SUS DATOS PERSONALES:</h3>
                    <ol className="Aviso-list">
                        <li>Finalidades Necesarias:</li>
                    </ol>
                    <p className="Aviso-paragraph">Los datos personales que recabamos de usted los utilizaremos para las siguientes finalidades que son necesarias para los productos o servicios que solicita de nosotros: para hacer posible que usted pueda comprar una propiedad en el desarrollo inmobiliario “Wise Living Cañada”, para formalizar y llevar a cabo su operación de compraventa residencial, para facilitar el cierre de su compra, para ayudarle a instalarse y disfrutar su propiedad y para cumplir con obligaciones derivadas de la relación jurídica que tengamos con usted, incluyendo con leyes y reglamentos en materia de prevención de lavado de dinero.</p>
                    <p className="Aviso-paragraph">Para llevar a cabo las finalidades descritas en este aviso de privacidad, utilizaremos los datos personales de identificación, de contacto y financieros que usted nos proporcione ya sea electrónicamente, por escrito o verbalmente. La Empresa no recaba ni trata datos personales sensibles.</p>
                    <ol className="Aviso-list" start="2">
                        <li>Finalidades Accesorias:</li>
                    </ol>
                    <p className="Aviso-paragraph">Asimismo, sus datos personales serán utilizados con las siguientes finalidades comerciales y de promoción:</p>
                    <ol className="Aviso-list Aviso-list--regular">
                        <li>Dar seguimiento a sus peticiones, sugerencias, reclamaciones y/o cualquier otra solicitud; y </li>
                        <li>Ser contactado y enviar información para darle a conocer información comercial de nuestra empresa y/o de terceros, entre la que se destaca información de nuevos productos, servicios, eventos, evaluación de la calidad en nuestra atención a clientes, información de nuestros socios de negocios, estudios internos, incluyendo cualquier acción de mercadotecnia, publicidad, estadística y de prospección comercial.</li>
                        <li>Para realizar investigación de mercado y el desarrollo de productos para que podamos entender sus necesidades como comprador de una residencia. </li>
                    </ol>
                    <p className="Aviso-paragraph">En caso de que sus datos personales no hubieren sido recabados de manera directa o personal, se le comunica que tendrá un plazo de 5 (cinco) días hábiles para que, de ser el caso, manifieste su negativa para el tratamiento de sus datos personales en relación a las finalidades que no son necesarias, ni han dado origen a la relación jurídica o comercial con La Empresa. </p>
                    <p className="Aviso-paragraph">En caso de que usted no desee que sus datos personales sean tratados para las finalidades accesorias antes descrita, usted podrá contactarnos en cualquier momento, para limitar dicho tratamiento, a través de nuestro correo electrónico contacto@wiseliving.com.mx.</p>
                    <h3 className="Aviso-title Aviso-title--left">TRANSFERENCIA DE DATOS PERSONALES:</h3>
                    <p className="Aviso-paragraph">Podremos transferir sus datos personales a terceros según sea permitido o requerido por ley. Para facilitar el cierre de su propiedad, y salvo que usted solicite lo contrario enviando un correo a contacto@wiseliving.com.mx, también podremos compartir sus datos personales con cualquier agente de escrow, notario público, fiduciario, compañía de seguro de título, asesores y otras partes involucradas según sea razonablemente necesario para que cada uno de ellos cumpla con sus respectivas funciones en completar dicho cierre y cumpla con sus obligaciones bajo las leyes y reglamentos aplicables.</p>
                    <p className="Aviso-paragraph">Sus datos serán tratados bajo estrictas medidas de seguridad tecnológicas, físicas y administrativas que garanticen su confidencialidad para prevenir el uso o divulgación indebida de los mismos.</p>
                    <h3 className="Aviso-title Aviso-title--left">DERECHOS ARCO:</h3>
                    <p className="Aviso-paragraph">Usted tiene derecho a conocer qué datos personales tenemos de usted y para qué los utilizamos (Acceso); a solicitar la corrección de su información personal en caso de que esté desactualizada, sea inexacta o incompleta (Rectificación); a que la eliminemos de nuestra bases de datos cuando considere que la misma no está siendo utilizada conforme a las leyes aplicables (Cancelación); y a oponerse al uso de sus datos personales para fines específicos (Oposición). Estos derechos se conocen como derechos ARCO.</p>
                    <p className="Aviso-paragraph">Para ejercer sus derechos ARCO, usted deberá presentar una solicitud a nuestro departamento de protección de datos personales mediante correo electrónico a la dirección contacto@wiseliving.com.mx. Su solicitud deberá ir acompañada de por lo menos: (a) nombre completo, domicilio y correo electrónico; (b) copia de una identificación oficial vigente; (c) en caso de ser aplicable, nombre completo del representante legal, copia de una identificación oficial vigente del representante legal y copia del instrumento público o carta poder firmada ante dos testigos que acredite la representación legal; (d) una descripción clara de los datos personales respecto de los que busca ejercer alguno de los derechos antes mencionados; (e) la descripción clara y precisa del derecho que desea ejercitar; y, (f) cualquier otro elemento que facilite la localización de los datos personales.</p>
                    <p className="Aviso-paragraph">En el caso de solicitudes de rectificación de datos personales, usted deberá indicar las modificaciones a realizarse y acompañar la documentación que sustente su petición. En caso de que la información proporcionada en la solicitud sea insuficiente o errónea, o bien, no se acompañen los documentos necesarios, dentro de los 5 (cinco) días hábiles siguientes a la recepción de la solicitud, podremos requerirle que aporte los elementos o documentos necesarios para dar trámite a la misma. Usted contará con 10 (diez) días hábiles para atender el requerimiento, contados a partir del día siguiente a aquél en que lo haya recibido. De no dar respuesta en dicho plazo, se tendrá por no presentada la solicitud correspondiente.</p>
                    <p className="Aviso-paragraph">Una vez presentada su solicitud, el departamento de protección de datos personales en un término de 20 (veinte) días hábiles emitirá una resolución, la cual le será notificada por los medios de contacto establecidos en la solicitud.</p>
                    <p className="Aviso-paragraph">Una vez emitida la resolución y en caso de que la misma sea calificada como procedente (parcial o totalmente) el departamento de protección de datos contará con un término de 15 (quince) días hábiles para adoptar la resolución.</p>
                    <p className="Aviso-paragraph">Los términos indicados en los párrafos que anteceden podrán ser ampliados una sola vez por periodos iguales, en caso de ser necesario situación que le deberá de ser notificada por los medios de contacto establecidos en la solicitud.</p>
                    <p className="Aviso-paragraph">El ejercicio de los Derechos ARCO será gratuito, no obstante si se reitera su solicitud en un periodo menor a doce meses, los costos serán de tres días de Salario Mínimo General Vigente en el Distrito Federal, más el Impuesto al Valor Agregado, a menos que existan modificaciones sustanciales al Aviso de Privacidad que motiven nuevas Solicitudes de Ejercicio de Derechos ARCO. Usted deberá de cubrir los gastos justificados de envío o el costo de reproducción en copias u otros formatos.</p>
                    <p className="Aviso-paragraph">Usted podrá dejar de recibir mensajes promocionales solicitándolo a nuestro correo contacto@wiseliving.com.mx.</p>
                    <h3 className="Aviso-title Aviso-title--left">LIMITACIÓN DE USO Y DIVULGACIÓN / REVOCACIÓN DEL CONSENTIMIENTO:</h3>
                    <p className="Aviso-paragraph">Para limitar el uso o divulgación de sus datos personales, así como para manifestar su negativa para el tratamiento de sus datos y revocar su consentimiento, deberá presentar su solicitud a nuestro encargado de privacidad, mediante correo electrónico al correo electrónico contacto@wiseliving.com.mx, que deberá contener por lo menos: (a) nombre y domicilio u otro medio para comunicarle la respuesta a su solicitud; (b) los documentos que acrediten su identidad o, en su caso, la representación legal; (c) la descripción clara y precisa del derecho que desea ejercitar; (d) tratándose de revocación de consentimiento, la manifestación expresa para revocar su consentimiento al tratamiento de sus datos personales y por tanto, para que se suspenda su uso; y (e) cualquier otro elemento que facilite la localización de los datos personales.</p>
                    <h3 className="Aviso-title Aviso-title--left">MODIFICACIONES AL AVISO DE PRIVACIDAD:</h3>
                    <p className="Aviso-paragraph">El presente aviso de privacidad puede sufrir modificaciones, cambios y/o actualizaciones derivadas de nuevos requerimientos legales; de nuestras propias necesidades por los productos o servicios que ofrecemos; de nuestras prácticas de privacidad; de cambios en nuestro modelo de negocio, o por otras causas.</p>
                    <p className="Aviso-paragraph">Nos comprometemos a mantenerlo informado sobre los cambios que pueda sufrir el presente aviso de privacidad.</p>
                    <p className="Aviso-paragraph">Las modificaciones serán oportunamente informadas a través de: (i) la página web: www.wiseliving.com.mx ; (ii) cualquier otro medio de comunicación oral, impreso o electrónico que La Empresa determine para tal efecto, (iii) o se las haremos llegar al último correo electrónico que nos haya proporcionado.</p>
                    <h3 className="Aviso-title Aviso-title--left">MECANISMOS DE SEGURIDAD:</h3>
                    <p className="Aviso-paragraph">Para garantizar el correcto resguardo de sus datos personales y para dar pleno cumplimiento a las obligaciones que la Ley, el Reglamento y los Lineamientos establecen, se le informa que La Empresa tiene implementadas las medidas de seguridad, administrativas, técnicas y físicas necesarias y suficientes para la correcta protección de sus datos personales.</p>
                    <h3 className="Aviso-title Aviso-title--left">USO DE COOKIES Y WEB BEACONS:</h3>
                    <p className="Aviso-paragraph">Las cookies son archivos de texto que son descargados automáticamente y almacenados en el disco duro del equipo de cómputo del usuario al navegar en una página de Internet específica, que permiten recordar al servidor de Internet algunos datos sobre este usuario, entre ellos, sus preferencias para la visualización de las páginas en ese servidor, nombre y contraseña.</p>
                    <p className="Aviso-paragraph">Por su parte, las web beacons son imágenes insertadas en una página de Internet o correo electrónico, que puede ser utilizado para monitorear el comportamiento de un visitante, como almacenar información sobre la dirección IP del usuario, duración del tiempo de interacción en dicha página y el tipo de navegador utilizado, entre otros.</p>
                    <p className="Aviso-paragraph">Le informamos que utilizamos cookies y web beacons para obtener la siguiente información personal cuando visita nuestra página web:
                        <ol>
                            <li>Su tipo de navegador y sistema operativo.</li>
                            <li>Las páginas de Internet que visita.</li>
                            <li>Los vínculos que sigue.</li>
                            <li>La dirección IP.</li>
                            <li>El sitio que visitó antes de entrar al nuestro.</li>
                        </ol>
                    </p>
                    <p className="Aviso-paragraph">Estas cookies y otras tecnologías pueden ser deshabilitadas.</p>
                    <h3 className="Aviso-title Aviso-title--left">DENUNCIAS:</h3>
                    <p className="Aviso-paragraph">Si usted considera que su derecho de protección de datos personales ha sido lesionado por alguna conducta de nuestros empleados o de nuestras actuaciones o respuestas, presume que en el tratamiento de sus datos personales existe alguna violación a las disposiciones previstas en la Ley, el Reglamento o los Lineamientos, podrá interponer la queja o denuncia correspondiente ante el INAI, para mayor información visite www.inai.org.mx .</p>
                    <p className="Aviso-paragraph">Última fecha de actualización: 14 de Mayo de 2018.</p>
                </div>
                <Footer />
            </section>
        );
    }
}